### ISSUE TITLE
No Internet CONNECTION.

### ISSUE THREAD

**Issue by katsaGeorge** [Anton2319/Anton2319#3]
I have done everything as you did and when i run the app I turn on the vpn but i dont have internet connection. Do you have any idea about that?

**Comment by Anton2319** [comment]
First of all, this is the repository for my website https://anton2319.ru, please recreate your issue in https://github.com/Anton2319/WireGuardExamples if it is still relevant. Second of all, provide your Wireguard config in your new issue and check if it works in the official WG app
